// This file was auto-generated by Fern from our API Definition.

import * as errors from "../../errors/index.js";
import * as Auth0MyAccount from "../index.js";
import * as core from "../../core/index.js";

export class BadRequestError extends errors.Auth0MyAccountError {
    constructor(body: Auth0MyAccount.ErrorResponse, rawResponse?: core.RawResponse) {
        super({
            message: "BadRequestError",
            statusCode: 400,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, BadRequestError.prototype);
    }
}
