// This file was auto-generated by Fern from our API Definition.

export class Auth0MyAccountTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, Auth0MyAccountTimeoutError.prototype);
    }
}
