// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as MyAccount from "../../../index.js";

export declare namespace FactorsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Factors
 */
export class FactorsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<FactorsClient.Options>;

    constructor(options: FactorsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List of factors enabled for the Auth0 tenant and available for enrollment by this user.
     *
     * @param {FactorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyAccount.BadRequestError}
     * @throws {@link MyAccount.UnauthorizedError}
     * @throws {@link MyAccount.ForbiddenError}
     * @throws {@link MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.factors.list()
     */
    public list(
        requestOptions?: FactorsClient.RequestOptions,
    ): core.HttpResponsePromise<MyAccount.ListFactorsResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: FactorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyAccount.ListFactorsResponseContent>> {
        const _metadata: core.EndpointMetadata = { security: [{ "Bearer-DPoP": ["read:me:factors"] }] };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyAccountEnvironment.Default,
                "factors",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as MyAccount.ListFactorsResponseContent, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyAccount.BadRequestError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new MyAccount.UnauthorizedError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyAccount.ForbiddenError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyAccount.TooManyRequestsError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyAccountError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/factors");
    }
}
