// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as MyAccount from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace ConnectedAccounts {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ConnectedAccounts {
    protected readonly _options: ConnectedAccounts.Options;

    constructor(_options: ConnectedAccounts.Options) {
        this._options = _options;
    }

    /**
     * Start an authorization flow to link the authenticated user's account with an external identity provider.
     *
     * @param {MyAccount.CreateConnectedAccountsRequestContent} request
     * @param {ConnectedAccounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyAccount.BadRequestError}
     * @throws {@link MyAccount.UnauthorizedError}
     * @throws {@link MyAccount.ForbiddenError}
     * @throws {@link MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.connectedAccounts.create({
     *         connection: "connection",
     *         redirect_uri: "redirect_uri"
     *     })
     */
    public create(
        request: MyAccount.CreateConnectedAccountsRequestContent,
        requestOptions?: ConnectedAccounts.RequestOptions,
    ): core.HttpResponsePromise<MyAccount.CreateConnectedAccountsResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: MyAccount.CreateConnectedAccountsRequestContent,
        requestOptions?: ConnectedAccounts.RequestOptions,
    ): Promise<core.WithRawResponse<MyAccount.CreateConnectedAccountsResponseContent>> {
        const _metadata: core.EndpointMetadata = { security: [{ "Bearer-DPoP": ["create:me:connected_accounts"] }] };
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader(_metadata) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyAccountEnvironment.Default,
                "connected-accounts/connect",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyAccount.CreateConnectedAccountsResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyAccount.BadRequestError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new MyAccount.UnauthorizedError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyAccount.ForbiddenError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyAccount.TooManyRequestsError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyAccountError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MyAccountError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MyAccountTimeoutError(
                    "Timeout exceeded when calling POST /connected-accounts/connect.",
                );
            case "unknown":
                throw new errors.MyAccountError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Complete a previously started authorization flow to link the authenticated user's account with an external identity provider.
     *
     * @param {MyAccount.CompleteConnectedAccountsRequestContent} request
     * @param {ConnectedAccounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyAccount.BadRequestError}
     * @throws {@link MyAccount.UnauthorizedError}
     * @throws {@link MyAccount.ForbiddenError}
     * @throws {@link MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.connectedAccounts.complete({
     *         auth_session: "auth_session",
     *         connect_code: "connect_code",
     *         redirect_uri: "redirect_uri"
     *     })
     */
    public complete(
        request: MyAccount.CompleteConnectedAccountsRequestContent,
        requestOptions?: ConnectedAccounts.RequestOptions,
    ): core.HttpResponsePromise<MyAccount.CompleteConnectedAccountsResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__complete(request, requestOptions));
    }

    private async __complete(
        request: MyAccount.CompleteConnectedAccountsRequestContent,
        requestOptions?: ConnectedAccounts.RequestOptions,
    ): Promise<core.WithRawResponse<MyAccount.CompleteConnectedAccountsResponseContent>> {
        const _metadata: core.EndpointMetadata = { security: [{ "Bearer-DPoP": ["create:me:connected_accounts"] }] };
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader(_metadata) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyAccountEnvironment.Default,
                "connected-accounts/complete",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyAccount.CompleteConnectedAccountsResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyAccount.BadRequestError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new MyAccount.UnauthorizedError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyAccount.ForbiddenError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyAccount.TooManyRequestsError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyAccountError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MyAccountError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MyAccountTimeoutError(
                    "Timeout exceeded when calling POST /connected-accounts/complete.",
                );
            case "unknown":
                throw new errors.MyAccountError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(endpointMetadata: core.EndpointMetadata): Promise<string> {
        return `Bearer ${await core.EndpointSupplier.get(this._options.token, { endpointMetadata })}`;
    }
}
