// This file was auto-generated by Fern from our API Definition.

/** The access type, always 'offline' */
export const AccessTypeEnum = {
    Offline: "offline",
} as const;
export type AccessTypeEnum = (typeof AccessTypeEnum)[keyof typeof AccessTypeEnum];
