// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface AuthenticationMethodWebAuthn extends MyAccount.AuthenticationMethodMfaBase {
    /** The friendly name of the authentication method */
    name?: string;
    /** The ID of the credential */
    key_id: string;
    /** The public key */
    public_key: string;
}
