// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface AuthenticationMethodPhone extends MyAccount.AuthenticationMethodMfaBase {
    /** The friendly name of the authentication method */
    name?: string | undefined;
    /** The destination phone number used to send verification codes via text and voice. */
    phone_number: string;
    preferred_authentication_method: MyAccount.PhoneAuthenticationMethodEnum;
}
