// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface AuthenticationMethodBase {
    /** The unique identifier of the authentication method */
    id: string;
    /** The date and time when the authentication method was created */
    created_at: string;
    usage: MyAccount.Usage;
}
