// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface AuthenticationMethodPassword extends MyAccount.AuthenticationMethodBase {
    /** The ID of the user identity linked with the authentication method */
    identity_user_id: string;
    /** The date of the last password reset */
    last_password_reset?: string | undefined;
}
