// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface AuthenticationMethodMfaPushNotification extends MyAccount.AuthenticationMethodMfaBase {
    /** The friendly name of the authentication method */
    name?: string | undefined;
}
