// This file was auto-generated by Fern from our API Definition.

/** The authenticator attachment method */
export const AuthenticatorAttachmentEnum = {
    Platform: "platform",
    CrossPlatform: "cross-platform",
} as const;
export type AuthenticatorAttachmentEnum =
    | (typeof AuthenticatorAttachmentEnum)[keyof typeof AuthenticatorAttachmentEnum]
    | string;
