// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export type AuthenticationMethod =
    | MyAccount.AuthenticationMethodPassword
    | MyAccount.AuthenticationMethodPasskey
    | MyAccount.AuthenticationMethodMfaRecoveryCode
    | MyAccount.AuthenticationMethodMfaPushNotification
    | MyAccount.AuthenticationMethodMfaTotp
    | MyAccount.AuthenticationMethodWebAuthnPlatform
    | MyAccount.AuthenticationMethodWebAuthnRoaming
    | MyAccount.AuthenticationMethodPhone
    | MyAccount.AuthenticationMethodEmail;
