// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface AuthenticatorAttestationResponse {
    authenticatorAttachment?: Auth0MyAccount.AuthenticatorAttachmentEnum;
    clientExtensionResults?: Auth0MyAccount.ClientExtensionResults;
    id: string;
    rawId: string;
    response: Auth0MyAccount.AuthenticatorAttestationResponseData;
    type: "public-key";
}
