// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface AuthenticatorAttestationResponse {
    authenticatorAttachment?: MyAccount.AuthenticatorAttachmentEnum;
    clientExtensionResults?: MyAccount.ClientExtensionResults;
    id: string;
    rawId: string;
    response: MyAccount.AuthenticatorAttestationResponseData;
    type: "public-key";
}
