// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface AuthenticationMethodMfaBase extends MyAccount.AuthenticationMethodBase {
    /** The authentication method status */
    confirmed: boolean;
}
