// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface AuthenticationMethodEmail extends MyAccount.AuthenticationMethodMfaBase {
    /** The friendly name of the authentication method */
    name?: string | undefined;
    /** The email address used to send verification messages. */
    email: string;
}
