// This file was auto-generated by Fern from our API Definition.

export interface AuthenticatorAttestationResponseData {
    attestationObject: string;
    clientDataJSON: string;
    transports?: string[];
}
