// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface AuthenticatorAttestationResponse {
    authenticatorAttachment?: MyAccount.AuthenticatorAttachmentEnum | undefined;
    clientExtensionResults?: MyAccount.ClientExtensionResults | undefined;
    id: string;
    rawId: string;
    response: MyAccount.AuthenticatorAttestationResponseData;
    type: AuthenticatorAttestationResponse.Type;
}

export namespace AuthenticatorAttestationResponse {
    export const Type = {
        PublicKey: "public-key",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
