// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface AuthenticatorSelection {
    residentKey?: Auth0MyAccount.ResidentKeyEnum;
    userVerification?: Auth0MyAccount.UserVerificationEnum;
}
