// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface AuthenticationMethodMfaBase extends Auth0MyAccount.AuthenticationMethodBase {
    /** The authentication method status */
    confirmed: boolean;
}
