// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export type AuthenticationMethodMfaPushNotification = Auth0MyAccount.AuthenticationMethodMfaBase;
