// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface CompleteConnectedAccountsResponseContent {
    /** The unique identifier of the connected account */
    id: string;
    /** The connection name */
    connection: string;
    access_type: Auth0MyAccount.AccessTypeEnum;
    /** Array of scopes granted */
    scopes?: string[];
    /** ISO date string of when the connected account was created */
    created_at: string;
    /** ISO date string of when the refresh token expires (optional) */
    expires_at?: string;
}
