// This file was auto-generated by Fern from our API Definition.

export interface ConnectedAccountConnection {
    /** The name of the connection. */
    name: string;
    /** The strategy used by the connection (e.g., 'oauth2', 'oidc'). */
    strategy: string;
    /** The available scopes for this connection. */
    scopes?: string[];
}
