// This file was auto-generated by Fern from our API Definition.

/** The access type for to the connected account. */
export const ConnectedAccountAccessTypeEnum = {
    Offline: "offline",
} as const;
export type ConnectedAccountAccessTypeEnum =
    (typeof ConnectedAccountAccessTypeEnum)[keyof typeof ConnectedAccountAccessTypeEnum];
