// This file was auto-generated by Fern from our API Definition.

/**
 * Parameters to be used with the connect URI.
 */
export interface ConnectParams {
    /** The ticket identifier to be used with the connection URI. */
    ticket: string;
}
