// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface ConnectedAccount {
    /** The unique identifier for the connected account. */
    id: string;
    /** The name of the connection associated with the account. */
    connection: string;
    access_type: Auth0MyAccount.ConnectedAccountAccessTypeEnum;
    /** The scopes granted for this connected account. */
    scopes: string[];
    /** ISO 8601 timestamp when the connected account was created. */
    created_at: string;
    /** ISO 8601 timestamp when the connected account expires. */
    expires_at?: string;
}
