// This file was auto-generated by Fern from our API Definition.

export interface CreateWebAuthnRoamingAuthenticationMethod {
    /** Authentication method type (factor) */
    type: CreateWebAuthnRoamingAuthenticationMethod.Type;
}

export namespace CreateWebAuthnRoamingAuthenticationMethod {
    /** Authentication method type (factor) */
    export const Type = {
        WebauthnRoaming: "webauthn-roaming",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
