// This file was auto-generated by Fern from our API Definition.

export interface CreateEmailAuthenticationMethod {
    /** The email address to use for sending one-time codes. */
    email: string;
}
