// This file was auto-generated by Fern from our API Definition.

export interface CreatePushNotificationAuthenticationMethod {
    /** Authentication method type (factor) */
    type: "push-notification";
}
