// This file was auto-generated by Fern from our API Definition.

export interface CreatePasskeyAuthenticationMethod {
    /** Authentication method type (factor) */
    type: "passkey";
    /** Connection name */
    connection?: string;
    /** The ID of the user identity linked with the authentication method */
    identity_user_id?: string;
}
