// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export type CreateAuthenticationMethodResponseContent =
    | MyAccount.PasskeyCreationResponse
    | MyAccount.WebAuthnCreationResponse
    | MyAccount.MfaBaseCreationResponse
    | MyAccount.QrCodeCreationResponse
    | MyAccount.RecoveryCodeCreationResponse;
