// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface CreateConnectedAccountsResponseContent {
    /** The base URI to initiate the account connection flow. */
    connect_uri: string;
    /** The authentication session identifier. */
    auth_session: string;
    connect_params: Auth0MyAccount.ConnectParams;
    /** The number of seconds until the ticket expires. */
    expires_in: number;
}
