// This file was auto-generated by Fern from our API Definition.

export interface CreateEmailAuthenticationMethod {
    /** Authentication method type (factor) */
    type: "email";
    /** The email address to use for sending one-time codes. */
    email: string;
}
