// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

/**
 * Request content for creating an authentication method
 */
export type CreateAuthenticationMethodRequestContent =
    | Auth0MyAccount.CreatePasskeyAuthenticationMethod
    | Auth0MyAccount.CreateWebAuthnPlatformAuthenticationMethod
    | Auth0MyAccount.CreateWebAuthnRoamingAuthenticationMethod
    | Auth0MyAccount.CreateTotpAuthenticationMethod
    | Auth0MyAccount.CreatePushNotificationAuthenticationMethod
    | Auth0MyAccount.CreateRecoveryCodeAuthenticationMethod
    | Auth0MyAccount.CreateEmailAuthenticationMethod
    | Auth0MyAccount.CreatePhoneAuthenticationMethod;
