// This file was auto-generated by Fern from our API Definition.

export interface CreateTotpAuthenticationMethod {
    /** Authentication method type (factor) */
    type: CreateTotpAuthenticationMethod.Type;
}

export namespace CreateTotpAuthenticationMethod {
    /** Authentication method type (factor) */
    export const Type = {
        Totp: "totp",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
