// This file was auto-generated by Fern from our API Definition.

export interface CreateWebAuthnPlatformAuthenticationMethod {
    /** Authentication method type (factor) */
    type: "webauthn-platform";
}
