// This file was auto-generated by Fern from our API Definition.

export interface CreateRecoveryCodeAuthenticationMethod {
    /** Authentication method type (factor) */
    type: "recovery-code";
}
