// This file was auto-generated by Fern from our API Definition.

export interface CreateEmailAuthenticationMethod {
    /** Authentication method type (factor) */
    type: CreateEmailAuthenticationMethod.Type;
    /** The email address to use for sending one-time codes. */
    email: string;
}

export namespace CreateEmailAuthenticationMethod {
    /** Authentication method type (factor) */
    export const Type = {
        Email: "email",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
