// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface CreatePhoneAuthenticationMethod {
    /** Authentication method type (factor) */
    type: "phone";
    /** The destination phone number used to send verification codes via text and voice. */
    phone_number: string;
    /** The preferred communication method. */
    preferred_authentication_method?: Auth0MyAccount.PhoneAuthenticationMethodEnum;
}
