// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export type CreateAuthenticationMethodResponseContent =
    | Auth0MyAccount.PasskeyCreationResponse
    | Auth0MyAccount.WebAuthnCreationResponse
    | Auth0MyAccount.MfaBaseCreationResponse
    | Auth0MyAccount.QrCodeCreationResponse
    | Auth0MyAccount.RecoveryCodeCreationResponse;
