// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

/**
 * Request content for creating an authentication method
 */
export type CreateAuthenticationMethodRequestContent =
    | MyAccount.CreatePasskeyAuthenticationMethod
    | MyAccount.CreateWebAuthnPlatformAuthenticationMethod
    | MyAccount.CreateWebAuthnRoamingAuthenticationMethod
    | MyAccount.CreateTotpAuthenticationMethod
    | MyAccount.CreatePushNotificationAuthenticationMethod
    | MyAccount.CreateRecoveryCodeAuthenticationMethod
    | MyAccount.CreateEmailAuthenticationMethod
    | MyAccount.CreatePhoneAuthenticationMethod;
