// This file was auto-generated by Fern from our API Definition.

export interface CreateWebAuthnPlatformAuthenticationMethod {
    /** Authentication method type (factor) */
    type: CreateWebAuthnPlatformAuthenticationMethod.Type;
}

export namespace CreateWebAuthnPlatformAuthenticationMethod {
    /** Authentication method type (factor) */
    export const Type = {
        WebauthnPlatform: "webauthn-platform",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
