// This file was auto-generated by Fern from our API Definition.

export interface CreateRecoveryCodeAuthenticationMethod {
    /** Authentication method type (factor) */
    type: CreateRecoveryCodeAuthenticationMethod.Type;
}

export namespace CreateRecoveryCodeAuthenticationMethod {
    /** Authentication method type (factor) */
    export const Type = {
        RecoveryCode: "recovery-code",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
