// This file was auto-generated by Fern from our API Definition.

export interface CreatePushNotificationAuthenticationMethod {
    /** Authentication method type (factor) */
    type: CreatePushNotificationAuthenticationMethod.Type;
}

export namespace CreatePushNotificationAuthenticationMethod {
    /** Authentication method type (factor) */
    export const Type = {
        PushNotification: "push-notification",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
