// This file was auto-generated by Fern from our API Definition.

/** Credential device type for passkey authentication methods */
export const CredentialDeviceTypeEnum = {
    MultiDevice: "multi_device",
    SingleDevice: "single_device",
} as const;
export type CredentialDeviceTypeEnum = (typeof CredentialDeviceTypeEnum)[keyof typeof CredentialDeviceTypeEnum];
