// This file was auto-generated by Fern from our API Definition.

/** Suggests how the IdP should display the authentication interface to the user. */
export const DisplayEnum = {
    Page: "page",
    Popup: "popup",
    Touch: "touch",
    Wap: "wap",
} as const;
export type DisplayEnum = (typeof DisplayEnum)[keyof typeof DisplayEnum];
