// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface ErrorResponse {
    type: string;
    status: number;
    title: string;
    detail: string;
    validation_errors?: Auth0MyAccount.ValidationError[];
}
