// This file was auto-generated by Fern from our API Definition.

/** Authentication method type (factor) */
export const FactorTypeEnum = {
    Password: "password",
    Passkey: "passkey",
    WebauthnPlatform: "webauthn-platform",
    WebauthnRoaming: "webauthn-roaming",
    Totp: "totp",
    Phone: "phone",
    Email: "email",
    PushNotification: "push-notification",
    RecoveryCode: "recovery-code",
} as const;
export type FactorTypeEnum = (typeof FactorTypeEnum)[keyof typeof FactorTypeEnum] | string;
