// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface Factor {
    type: MyAccount.FactorTypeEnum;
    usage?: MyAccount.Usage;
}
