// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface Factor {
    type: Auth0MyAccount.FactorTypeEnum;
    usage?: Auth0MyAccount.Usage;
}
