// This file was auto-generated by Fern from our API Definition.

/**
 * When using a Google social or enterprise (Google Workspace) connection, include this parameter with the value `offline` to be able to refresh access tokens.
 */
export type GoogleAccessTypeEnum = "offline";
