// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface IdentityAuthenticationMethodBase {
    connection?: MyAccount.Connection | undefined;
    identity_user_id?: MyAccount.IdentityUserId | undefined;
}
