// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface ListAuthenticationMethodsResponseContent {
    authentication_methods: Auth0MyAccount.AuthenticationMethod[];
}
