// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface ListConnectedAccountsConnectionsResponseContent {
    connections: Auth0MyAccount.ConnectedAccountConnection[];
    /** The token to retrieve the next page of connections (if there is one) */
    next?: string;
}
