// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface ListConnectedAccountsResponseContent {
    accounts: Auth0MyAccount.ConnectedAccount[];
    /** The token to retrieve the next page of connected accounts (if there is one) */
    next?: string;
}
