// This file was auto-generated by Fern from our API Definition.

export interface MfaBaseCreationResponse {
    /** The unique identifier for the authentication method. */
    id: string;
    /** The unique session identifier for the enrollment. */
    auth_session: string;
}
