// This file was auto-generated by Fern from our API Definition.

/** Behavior when password exceeds maximum length */
export const PasswordMaxLengthExceededEnum = {
    Truncate: "truncate",
    Error: "error",
} as const;
export type PasswordMaxLengthExceededEnum =
    (typeof PasswordMaxLengthExceededEnum)[keyof typeof PasswordMaxLengthExceededEnum];
