// This file was auto-generated by Fern from our API Definition.

/** Default dictionary to use for checking weak passwords */
export const PasswordDictionaryDefaultEnum = {
    En10K: "en_10k",
    En100K: "en_100k",
} as const;
export type PasswordDictionaryDefaultEnum =
    (typeof PasswordDictionaryDefaultEnum)[keyof typeof PasswordDictionaryDefaultEnum];
