// This file was auto-generated by Fern from our API Definition.

/**
 * Settings for blocking personal information in passwords
 */
export interface PasswordProfileDataPolicy {
    /** Whether to block personal information (name, email, etc.) in passwords */
    active: boolean;
    /** User profile fields to block from passwords (e.g., 'name', 'email', 'user_metadata.first') */
    blocked_fields: string[];
}
