// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface PasswordCreationResponse {
    /** The unique identifier for the password authentication method. */
    id: string;
    policy: MyAccount.PasswordAuthenticationMethodPolicy;
    /** The unique session identifier for the password change operation. */
    auth_session: string;
}
