// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface PasskeyCreationResponse {
    /** The unique session identifier for the enrollment. */
    auth_session: string;
    authn_params_public_key: Auth0MyAccount.PublicKeyCredentialCreationOptions;
}
