// This file was auto-generated by Fern from our API Definition.

/** Whether to allow 3 or more consecutive identical characters */
export const PasswordIdenticalCharactersEnum = {
    Allow: "allow",
    Block: "block",
} as const;
export type PasswordIdenticalCharactersEnum =
    (typeof PasswordIdenticalCharactersEnum)[keyof typeof PasswordIdenticalCharactersEnum];
