// This file was auto-generated by Fern from our API Definition.

/**
 * Password history enforcement settings
 */
export interface PasswordHistoryPolicy {
    /** Whether password history is enforced */
    active: boolean;
    /** Number of previous passwords to remember and prevent reuse */
    size: number;
}
