// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

/**
 * The password policy configuration for the connection in flexible format.
 */
export interface PasswordAuthenticationMethodPolicy {
    complexity: MyAccount.PasswordComplexityPolicy;
    profile_data: MyAccount.PasswordProfileDataPolicy;
    history: MyAccount.PasswordHistoryPolicy;
    dictionary: MyAccount.PasswordDictionaryPolicy;
}
