// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

/**
 * Password complexity requirements
 */
export interface PasswordComplexityPolicy {
    /** Minimum password length */
    min_length: number;
    /** Required character types */
    character_types: MyAccount.PasswordCharacterTypeEnum[];
    character_type_rule: MyAccount.PasswordCharacterTypeRuleEnum;
    identical_characters: MyAccount.PasswordIdenticalCharactersEnum;
    sequential_characters: MyAccount.PasswordSequentialCharactersEnum;
    max_length_exceeded: MyAccount.PasswordMaxLengthExceededEnum;
}
