// This file was auto-generated by Fern from our API Definition.

/** Character type for password complexity requirements */
export const PasswordCharacterTypeEnum = {
    Uppercase: "uppercase",
    Lowercase: "lowercase",
    Number: "number",
    Special: "special",
} as const;
export type PasswordCharacterTypeEnum = (typeof PasswordCharacterTypeEnum)[keyof typeof PasswordCharacterTypeEnum];
