// This file was auto-generated by Fern from our API Definition.

/** Whether to allow sequential characters */
export const PasswordSequentialCharactersEnum = {
    Allow: "allow",
    Block: "block",
} as const;
export type PasswordSequentialCharactersEnum =
    (typeof PasswordSequentialCharactersEnum)[keyof typeof PasswordSequentialCharactersEnum];
