// This file was auto-generated by Fern from our API Definition.

/** How character types are enforced in password complexity */
export const PasswordCharacterTypeRuleEnum = {
    All: "all",
    ThreeOfFour: "three_of_four",
} as const;
export type PasswordCharacterTypeRuleEnum =
    (typeof PasswordCharacterTypeRuleEnum)[keyof typeof PasswordCharacterTypeRuleEnum];
