// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

/**
 * Dictionary checking settings to block weak or banned passwords
 */
export interface PasswordDictionaryPolicy {
    /** Whether dictionary checking is enabled */
    active: boolean;
    default: MyAccount.PasswordDictionaryDefaultEnum;
}
