// This file was auto-generated by Fern from our API Definition.

/** Preferred authentication method for phone-based authentication */
export const PhoneAuthenticationMethodEnum = {
    Sms: "sms",
    Voice: "voice",
} as const;
export type PhoneAuthenticationMethodEnum =
    (typeof PhoneAuthenticationMethodEnum)[keyof typeof PhoneAuthenticationMethodEnum];
