// This file was auto-generated by Fern from our API Definition.

/** Controls whether the IdP should prompt the user for authentication or consent. */
export const PromptEnum = {
    None: "none",
    Login: "login",
    Consent: "consent",
    SelectAccount: "select_account",
} as const;
export type PromptEnum = (typeof PromptEnum)[keyof typeof PromptEnum];
