// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface PublicKeyCredentialParameter {
    alg: number;
    type: Auth0MyAccount.PublicKeyTypeEnum;
}
