// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface PublicKeyCredentialCreationOptions {
    authenticatorSelection?: MyAccount.AuthenticatorSelection;
    challenge: string;
    pubKeyCredParams: MyAccount.PublicKeyCredentialParameter[];
    rp: MyAccount.RelyingParty;
    timeout?: number;
    user: MyAccount.User;
}
