// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface PublicKeyCredentialCreationOptions {
    authenticatorSelection?: Auth0MyAccount.AuthenticatorSelection;
    challenge: string;
    pubKeyCredParams: Auth0MyAccount.PublicKeyCredentialParameter[];
    rp: Auth0MyAccount.RelyingParty;
    timeout?: number;
    user: Auth0MyAccount.User;
}
