// This file was auto-generated by Fern from our API Definition.

/** The public key credential type */
export const PublicKeyTypeEnum = {
    PublicKey: "public-key",
} as const;
export type PublicKeyTypeEnum = (typeof PublicKeyTypeEnum)[keyof typeof PublicKeyTypeEnum];
