// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface QrCodeCreationResponse extends Auth0MyAccount.MfaBaseCreationResponse {
    /** The URI for the QR code to be scanned by the authenticator. */
    barcode_uri: string;
    /** The manual input code for the authenticator in case QR codes cannot be used. */
    manual_input_code?: string;
}
