// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface RecoveryCodeCreationResponse extends Auth0MyAccount.MfaBaseCreationResponse {
    /** The recovery code value. */
    recovery_code: string;
}
