// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface RecoveryCodeCreationResponse extends MyAccount.MfaBaseCreationResponse {
    /** The recovery code value. */
    recovery_code: string;
}
