// This file was auto-generated by Fern from our API Definition.

/** The resident key requirement */
export const ResidentKeyEnum = {
    Required: "required",
} as const;
export type ResidentKeyEnum = (typeof ResidentKeyEnum)[keyof typeof ResidentKeyEnum];
