// This file was auto-generated by Fern from our API Definition.

/** Usage type for authentication factors */
export const UsageEnum = {
    Primary: "primary",
    Secondary: "secondary",
} as const;
export type UsageEnum = (typeof UsageEnum)[keyof typeof UsageEnum] | string;
