// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

/**
 * Primary and/or secondary factor
 */
export type Usage = Auth0MyAccount.UsageEnum[];
