// This file was auto-generated by Fern from our API Definition.

/** The user verification requirement */
export const UserVerificationEnum = {
    Required: "required",
    Preferred: "preferred",
    Discouraged: "discouraged",
} as const;
export type UserVerificationEnum = (typeof UserVerificationEnum)[keyof typeof UserVerificationEnum];
