// This file was auto-generated by Fern from our API Definition.

export interface ValidationError {
    detail: string;
    field?: string | undefined;
    pointer?: string | undefined;
    source?: string | undefined;
}
