// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

/**
 * Request content for verifying an authentication method
 */
export type VerifyAuthenticationMethodRequestContent =
    | MyAccount.VerifyPasskeyAuthenticationMethod
    | MyAccount.VerifyWebAuthnPlatformAuthenticationMethod
    | MyAccount.VerifyWebAuthnRoamingAuthenticationMethod
    | MyAccount.VerifyPushNotificationAuthenticationMethod
    | MyAccount.VerifyRecoveryCodeAuthenticationMethod
    | MyAccount.VerifyEmailAuthenticationMethod
    | MyAccount.VerifyPhoneAuthenticationMethod
    | MyAccount.VerifyTotpAuthenticationMethod;
