// This file was auto-generated by Fern from our API Definition.

export interface VerifyRecoveryCodeAuthenticationMethod {
    /** The unique session identifier for the enrollment as returned by POST /authentication-methods */
    auth_session: string;
}
