// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export type VerifyAuthenticationMethodResponseContent =
    | Auth0MyAccount.AuthenticationMethodPassword
    | Auth0MyAccount.AuthenticationMethodPasskey
    | Auth0MyAccount.AuthenticationMethodMfaRecoveryCode
    | Auth0MyAccount.AuthenticationMethodMfaPushNotification
    | Auth0MyAccount.AuthenticationMethodMfaTotp
    | Auth0MyAccount.AuthenticationMethodWebAuthnPlatform
    | Auth0MyAccount.AuthenticationMethodWebAuthnRoaming
    | Auth0MyAccount.AuthenticationMethodPhone
    | Auth0MyAccount.AuthenticationMethodEmail;
