// This file was auto-generated by Fern from our API Definition.

export interface VerifyTotpAuthenticationMethod {
    /** The unique session identifier for the enrollment as returned by POST /authentication-methods */
    auth_session: string;
    /** The one-time password code retrieved from the TOTP application. */
    otp_code: string;
}
