// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface VerifyWebAuthnPlatformAuthenticationMethod {
    /** The unique session identifier for the enrollment as returned by POST /authentication-methods */
    auth_session: string;
    authn_response: MyAccount.AuthenticatorAttestationResponse;
}
