// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface VerifyWebAuthnRoamingAuthenticationMethod {
    /** The unique session identifier for the enrollment as returned by POST /authentication-methods */
    auth_session: string;
    authn_response: Auth0MyAccount.AuthenticatorAttestationResponse;
}
