// This file was auto-generated by Fern from our API Definition.

export interface VerifyPasswordAuthenticationMethod {
    /** The unique session identifier for the password change operation as returned by POST /authentication-methods */
    auth_session: string;
    /** The new password to set for the user */
    new_password: string;
}
