// This file was auto-generated by Fern from our API Definition.

export interface VerifyPhoneAuthenticationMethod {
    /** The unique session identifier for the enrollment as returned by POST /authentication-methods */
    auth_session: string;
    /** The one-time password code sent to the phone number. */
    otp_code: string;
}
