// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

/**
 * Request content for verifying an authentication method
 */
export type VerifyAuthenticationMethodRequestContent =
    | Auth0MyAccount.VerifyPasskeyAuthenticationMethod
    | Auth0MyAccount.VerifyWebAuthnPlatformAuthenticationMethod
    | Auth0MyAccount.VerifyWebAuthnRoamingAuthenticationMethod
    | Auth0MyAccount.VerifyPushNotificationAuthenticationMethod
    | Auth0MyAccount.VerifyRecoveryCodeAuthenticationMethod
    | Auth0MyAccount.VerifyEmailAuthenticationMethod
    | Auth0MyAccount.VerifyPhoneAuthenticationMethod
    | Auth0MyAccount.VerifyTotpAuthenticationMethod;
