// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

export interface WebAuthnCreationResponse extends MyAccount.MfaBaseCreationResponse {
    authn_params_public_key: MyAccount.PublicKeyCredentialCreationOptions;
}
