// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyAccount from "../index.js";

export interface WebAuthnCreationResponse extends Auth0MyAccount.MfaBaseCreationResponse {
    authn_params_public_key: Auth0MyAccount.PublicKeyCredentialCreationOptions;
}
