// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as MyAccount from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace AuthenticationMethods {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AuthenticationMethods {
    protected readonly _options: AuthenticationMethods.Options;

    constructor(_options: AuthenticationMethods.Options) {
        this._options = _options;
    }

    /**
     * Updates a single authentication method
     *
     * @param {MyAccount.PathAuthenticationMethodId} authenticationMethodId - Authentication Method ID. This value is part of the Location header returned when creating an authentication method. It should be used as it is, without any modifications.
     * @param {MyAccount.UpdateAuthenticationMethodRequestContent} request
     * @param {AuthenticationMethods.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyAccount.BadRequestError}
     * @throws {@link MyAccount.UnauthorizedError}
     * @throws {@link MyAccount.ForbiddenError}
     * @throws {@link MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.authenticationMethods.update("authentication_method_id")
     */
    public update(
        authenticationMethodId: MyAccount.PathAuthenticationMethodId,
        request: MyAccount.UpdateAuthenticationMethodRequestContent = {},
        requestOptions?: AuthenticationMethods.RequestOptions,
    ): core.HttpResponsePromise<MyAccount.UpdateAuthenticationMethodResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__update(authenticationMethodId, request, requestOptions));
    }

    private async __update(
        authenticationMethodId: MyAccount.PathAuthenticationMethodId,
        request: MyAccount.UpdateAuthenticationMethodRequestContent = {},
        requestOptions?: AuthenticationMethods.RequestOptions,
    ): Promise<core.WithRawResponse<MyAccount.UpdateAuthenticationMethodResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [{ "Bearer-DPoP": ["update:me:authentication_methods"] }],
        };
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader(_metadata) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyAccountEnvironment.Default,
                `authentication-methods/${core.url.encodePathParam(authenticationMethodId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyAccount.UpdateAuthenticationMethodResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyAccount.BadRequestError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new MyAccount.UnauthorizedError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyAccount.ForbiddenError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyAccount.TooManyRequestsError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyAccountError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MyAccountError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MyAccountTimeoutError(
                    "Timeout exceeded when calling PATCH /authentication-methods/{authentication_method_id}.",
                );
            case "unknown":
                throw new errors.MyAccountError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(endpointMetadata: core.EndpointMetadata): Promise<string> {
        return `Bearer ${await core.EndpointSupplier.get(this._options.token, { endpointMetadata })}`;
    }
}
