// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as MyAccount from "../../../index.js";

export declare namespace AuthenticationMethodsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AuthenticationMethodsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AuthenticationMethodsClient.Options>;

    constructor(options: AuthenticationMethodsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     *
     * @param {AuthenticationMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyAccount.BadRequestError}
     * @throws {@link MyAccount.UnauthorizedError}
     * @throws {@link MyAccount.ForbiddenError}
     * @throws {@link MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.authenticationMethods.list()
     */
    public list(
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): core.HttpResponsePromise<MyAccount.ListAuthenticationMethodsResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyAccount.ListAuthenticationMethodsResponseContent>> {
        const _metadata: core.EndpointMetadata = { security: [{ "Bearer-DPoP": ["read:me:authentication_methods"] }] };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyAccountEnvironment.Default,
                "authentication-methods",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyAccount.ListAuthenticationMethodsResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyAccount.BadRequestError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new MyAccount.UnauthorizedError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyAccount.ForbiddenError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyAccount.TooManyRequestsError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyAccountError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/authentication-methods");
    }

    /**
     * Start the enrollment of a supported authentication method.
     *
     * @param {MyAccount.CreateAuthenticationMethodRequestContent} request
     * @param {AuthenticationMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyAccount.BadRequestError}
     * @throws {@link MyAccount.UnauthorizedError}
     * @throws {@link MyAccount.ForbiddenError}
     * @throws {@link MyAccount.UnsupportedMediaTypeError}
     * @throws {@link MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.authenticationMethods.create({
     *         type: "passkey"
     *     })
     */
    public create(
        request: MyAccount.CreateAuthenticationMethodRequestContent,
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): core.HttpResponsePromise<MyAccount.CreateAuthenticationMethodResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: MyAccount.CreateAuthenticationMethodRequestContent,
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyAccount.CreateAuthenticationMethodResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [{ "Bearer-DPoP": ["create:me:authentication_methods"] }],
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyAccountEnvironment.Default,
                "authentication-methods",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyAccount.CreateAuthenticationMethodResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyAccount.BadRequestError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new MyAccount.UnauthorizedError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyAccount.ForbiddenError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 415:
                    throw new MyAccount.UnsupportedMediaTypeError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyAccount.TooManyRequestsError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyAccountError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/authentication-methods");
    }

    /**
     * Retrieves a single authentication method belonging to the authenticated user.
     *
     * @param {MyAccount.PathAuthenticationMethodId} authentication_method_id - Authentication Method ID. This value is part of the Location header returned when creating an authentication method. It should be used as it is, without any modifications.
     * @param {AuthenticationMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyAccount.BadRequestError}
     * @throws {@link MyAccount.UnauthorizedError}
     * @throws {@link MyAccount.ForbiddenError}
     * @throws {@link MyAccount.NotFoundError}
     * @throws {@link MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.authenticationMethods.get("authentication_method_id")
     */
    public get(
        authentication_method_id: MyAccount.PathAuthenticationMethodId,
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): core.HttpResponsePromise<MyAccount.GetAuthenticationMethodResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__get(authentication_method_id, requestOptions));
    }

    private async __get(
        authentication_method_id: MyAccount.PathAuthenticationMethodId,
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyAccount.GetAuthenticationMethodResponseContent>> {
        const _metadata: core.EndpointMetadata = { security: [{ "Bearer-DPoP": ["read:me:authentication_methods"] }] };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyAccountEnvironment.Default,
                `authentication-methods/${core.url.encodePathParam(authentication_method_id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyAccount.GetAuthenticationMethodResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyAccount.BadRequestError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new MyAccount.UnauthorizedError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyAccount.ForbiddenError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyAccount.NotFoundError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyAccount.TooManyRequestsError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyAccountError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/authentication-methods/{authentication_method_id}",
        );
    }

    /**
     * Deletes a single authentication method belonging to the authenticated user.
     *
     * @param {MyAccount.PathAuthenticationMethodId} authentication_method_id - Authentication Method ID. This value is part of the Location header returned when creating an authentication method. It should be used as it is, without any modifications.
     * @param {AuthenticationMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyAccount.BadRequestError}
     * @throws {@link MyAccount.UnauthorizedError}
     * @throws {@link MyAccount.ForbiddenError}
     * @throws {@link MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.authenticationMethods.delete("authentication_method_id")
     */
    public delete(
        authentication_method_id: MyAccount.PathAuthenticationMethodId,
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(authentication_method_id, requestOptions));
    }

    private async __delete(
        authentication_method_id: MyAccount.PathAuthenticationMethodId,
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _metadata: core.EndpointMetadata = {
            security: [{ "Bearer-DPoP": ["delete:me:authentication_methods"] }],
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyAccountEnvironment.Default,
                `authentication-methods/${core.url.encodePathParam(authentication_method_id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyAccount.BadRequestError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new MyAccount.UnauthorizedError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyAccount.ForbiddenError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyAccount.TooManyRequestsError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyAccountError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/authentication-methods/{authentication_method_id}",
        );
    }

    /**
     * Updates a single authentication method
     *
     * @param {MyAccount.PathAuthenticationMethodId} authentication_method_id - Authentication Method ID. This value is part of the Location header returned when creating an authentication method. It should be used as it is, without any modifications.
     * @param {MyAccount.UpdateAuthenticationMethodRequestContent} request
     * @param {AuthenticationMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyAccount.BadRequestError}
     * @throws {@link MyAccount.UnauthorizedError}
     * @throws {@link MyAccount.ForbiddenError}
     * @throws {@link MyAccount.UnsupportedMediaTypeError}
     * @throws {@link MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.authenticationMethods.update("authentication_method_id")
     */
    public update(
        authentication_method_id: MyAccount.PathAuthenticationMethodId,
        request: MyAccount.UpdateAuthenticationMethodRequestContent = {},
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): core.HttpResponsePromise<MyAccount.UpdateAuthenticationMethodResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__update(authentication_method_id, request, requestOptions));
    }

    private async __update(
        authentication_method_id: MyAccount.PathAuthenticationMethodId,
        request: MyAccount.UpdateAuthenticationMethodRequestContent = {},
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyAccount.UpdateAuthenticationMethodResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [{ "Bearer-DPoP": ["update:me:authentication_methods"] }],
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyAccountEnvironment.Default,
                `authentication-methods/${core.url.encodePathParam(authentication_method_id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyAccount.UpdateAuthenticationMethodResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyAccount.BadRequestError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new MyAccount.UnauthorizedError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyAccount.ForbiddenError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 415:
                    throw new MyAccount.UnsupportedMediaTypeError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyAccount.TooManyRequestsError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyAccountError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/authentication-methods/{authentication_method_id}",
        );
    }

    /**
     * Confirm the enrollment of a supported authentication method.
     *
     * @param {MyAccount.PathAuthenticationMethodId} authentication_method_id - Authentication Method ID. This value is part of the Location header returned when creating an authentication method. It should be used as it is, without any modifications.
     * @param {MyAccount.VerifyAuthenticationMethodRequestContent} request
     * @param {AuthenticationMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyAccount.BadRequestError}
     * @throws {@link MyAccount.UnauthorizedError}
     * @throws {@link MyAccount.ForbiddenError}
     * @throws {@link MyAccount.UnsupportedMediaTypeError}
     * @throws {@link MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.authenticationMethods.verify("authentication_method_id", {
     *         auth_session: "auth_session",
     *         authn_response: {
     *             id: "id",
     *             rawId: "rawId",
     *             response: {
     *                 attestationObject: "attestationObject",
     *                 clientDataJSON: "clientDataJSON"
     *             },
     *             type: "public-key"
     *         }
     *     })
     */
    public verify(
        authentication_method_id: MyAccount.PathAuthenticationMethodId,
        request: MyAccount.VerifyAuthenticationMethodRequestContent,
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): core.HttpResponsePromise<MyAccount.VerifyAuthenticationMethodResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__verify(authentication_method_id, request, requestOptions));
    }

    private async __verify(
        authentication_method_id: MyAccount.PathAuthenticationMethodId,
        request: MyAccount.VerifyAuthenticationMethodRequestContent,
        requestOptions?: AuthenticationMethodsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyAccount.VerifyAuthenticationMethodResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [{ "Bearer-DPoP": ["create:me:authentication_methods"] }],
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyAccountEnvironment.Default,
                `authentication-methods/${core.url.encodePathParam(authentication_method_id)}/verify`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyAccount.VerifyAuthenticationMethodResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyAccount.BadRequestError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new MyAccount.UnauthorizedError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyAccount.ForbiddenError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 415:
                    throw new MyAccount.UnsupportedMediaTypeError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyAccount.TooManyRequestsError(
                        _response.error.body as MyAccount.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyAccountError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/authentication-methods/{authentication_method_id}/verify",
        );
    }
}
