// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../mock-server/MockServerPool";
import { MyAccountClient } from "../../src/Client";
import * as MyAccount from "../../src/api/index";

describe("AuthenticationMethods", () => {
    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { id: "id", created_at: "2024-01-15T09:30:00Z", usage: ["primary"] };
        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.update("authentication_method_id");
        expect(response).toEqual({
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.update("authentication_method_id");
        }).rejects.toThrow(MyAccount.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.update("authentication_method_id");
        }).rejects.toThrow(MyAccount.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.update("authentication_method_id");
        }).rejects.toThrow(MyAccount.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.update("authentication_method_id");
        }).rejects.toThrow(MyAccount.TooManyRequestsError);
    });
});
