// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../../src/api/index";
import { MyAccountClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AuthenticationMethodsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            authentication_methods: [
                {
                    type: "email",
                    id: "id",
                    created_at: "2024-01-15T09:30:00Z",
                    usage: ["primary"],
                    confirmed: true,
                    last_auth_at: "2024-01-15T09:30:00Z",
                    name: "name",
                    email: "email",
                },
                {
                    type: "phone",
                    id: "id",
                    created_at: "2024-01-15T09:30:00Z",
                    usage: ["primary"],
                    confirmed: true,
                    last_auth_at: "2024-01-15T09:30:00Z",
                    name: "name",
                    phone_number: "phone_number",
                    preferred_authentication_method: "sms",
                },
                {
                    type: "totp",
                    id: "id",
                    created_at: "2024-01-15T09:30:00Z",
                    usage: ["primary"],
                    confirmed: true,
                    last_auth_at: "2024-01-15T09:30:00Z",
                    name: "name",
                },
                {
                    type: "passkey",
                    id: "id",
                    created_at: "2024-01-15T09:30:00Z",
                    usage: ["primary"],
                    credential_backed_up: true,
                    credential_device_type: "multi_device",
                    identity_user_id: "identity_user_id",
                    key_id: "key_id",
                    public_key: "public_key",
                    transports: ["internal"],
                    user_agent: "Chrome 131.0.0 / Mac OS X 10.15.7",
                    user_handle: "user_handle",
                    aaguid: "aaguid",
                    relying_party_id: "relying_party_id",
                    last_auth_at: "2024-01-15T09:30:00Z",
                },
                {
                    type: "password",
                    id: "id",
                    created_at: "2024-01-15T09:30:00Z",
                    usage: ["primary"],
                    identity_user_id: "identity_user_id",
                    last_password_reset: "2024-01-15T09:30:00Z",
                },
                {
                    type: "webauthn-platform",
                    id: "id",
                    created_at: "2024-01-15T09:30:00Z",
                    usage: ["primary"],
                    confirmed: true,
                    last_auth_at: "2024-01-15T09:30:00Z",
                    name: "name",
                    key_id: "key_id",
                    public_key: "public_key",
                },
                {
                    type: "webauthn-roaming",
                    id: "id",
                    created_at: "2024-01-15T09:30:00Z",
                    usage: ["primary"],
                    confirmed: true,
                    last_auth_at: "2024-01-15T09:30:00Z",
                    name: "name",
                    key_id: "key_id",
                    public_key: "public_key",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/authentication-methods")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.list({
            type: "password",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/authentication-methods")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.list();
        }).rejects.toThrow(MyAccount.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/authentication-methods")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.list();
        }).rejects.toThrow(MyAccount.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/authentication-methods")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.list();
        }).rejects.toThrow(MyAccount.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/authentication-methods")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.list();
        }).rejects.toThrow(MyAccount.TooManyRequestsError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "phone", phone_number: "phone_number" };
        const rawResponseBody = { id: "phone|dev_XXXXXXXXXXXXXXXX", auth_session: "Fe26.2**05c400ed..." };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "phone",
            phone_number: "phone_number",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "email", email: "email" };
        const rawResponseBody = { id: "phone|dev_XXXXXXXXXXXXXXXX", auth_session: "Fe26.2**05c400ed..." };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "email",
            email: "email",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "totp" };
        const rawResponseBody = { id: "phone|dev_XXXXXXXXXXXXXXXX", auth_session: "Fe26.2**05c400ed..." };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "totp",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "push-notification" };
        const rawResponseBody = { id: "phone|dev_XXXXXXXXXXXXXXXX", auth_session: "Fe26.2**05c400ed..." };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "push-notification",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "recovery-code" };
        const rawResponseBody = { id: "phone|dev_XXXXXXXXXXXXXXXX", auth_session: "Fe26.2**05c400ed..." };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "recovery-code",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "password" };
        const rawResponseBody = { id: "phone|dev_XXXXXXXXXXXXXXXX", auth_session: "Fe26.2**05c400ed..." };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "password",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "passkey" };
        const rawResponseBody = { id: "phone|dev_XXXXXXXXXXXXXXXX", auth_session: "Fe26.2**05c400ed..." };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "passkey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "phone", phone_number: "phone_number" };
        const rawResponseBody = { id: "phone|dev_XXXXXXXXXXXXXXXX", auth_session: "Fe26.2**05c400ed..." };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "phone",
            phone_number: "phone_number",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "phone", phone_number: "phone_number" };
        const rawResponseBody = { id: "email|dev_XXXXXXXXXXXXXXXX", auth_session: "Fe26.2**05c400ed..." };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "phone",
            phone_number: "phone_number",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "phone", phone_number: "phone_number" };
        const rawResponseBody = {
            id: "totp|dev_XXXXXXXXXXXXXXXX",
            auth_session: "Fe26.2**05c400ed...",
            barcode_uri:
                "otpauth://totp/my-tenant:auth0%7C507f1f77bcf86cd799439011?secret=JBSWY3DPEHPK3PXP&issuer=my-tenant&algorithm=SHA1&digits=6&period=30",
            manual_input_code: "JBSWY3DPEHPK3PXP",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "phone",
            phone_number: "phone_number",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "phone", phone_number: "phone_number" };
        const rawResponseBody = {
            id: "push-notification|dev_XXXXXXXXXXXXXXXX",
            auth_session: "Fe26.2**05c400ed...",
            barcode_uri:
                "otpauth://totp/my-tenant:auth0%7C507f1f77bcf86cd799439011?secret=JBSWY3DPEHPK3PXP&issuer=my-tenant&algorithm=SHA1&digits=6&period=30",
            manual_input_code: "manual_input_code",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "phone",
            phone_number: "phone_number",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "phone", phone_number: "phone_number" };
        const rawResponseBody = {
            id: "recovery-code|dev_XXXXXXXXXXXXXXXX",
            auth_session: "Fe26.2**05c400ed...",
            recovery_code: "ABCDEFGHIJKLMNOPQRSTUVWX",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "phone",
            phone_number: "phone_number",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (13)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "phone", phone_number: "phone_number" };
        const rawResponseBody = {
            id: "password|new",
            policy: {
                complexity: {
                    min_length: 8,
                    character_types: ["lowercase", "uppercase", "number", "special"],
                    character_type_rule: "three_of_four",
                    identical_characters: "block",
                    sequential_characters: "block",
                    max_length_exceeded: "truncate",
                },
                profile_data: { active: true, blocked_fields: ["name", "email"] },
                history: { active: true, size: 5 },
                dictionary: { active: true, default: "en_10k" },
            },
            auth_session: "Fe26.2**05c400ed...",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "phone",
            phone_number: "phone_number",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (14)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "phone", phone_number: "phone_number" };
        const rawResponseBody = {
            auth_session: "Fe26.2**05c400ed...",
            authn_params_public_key: {
                authenticatorSelection: { residentKey: "required", userVerification: "preferred" },
                challenge: "dGVzdC1jaGFsbGVuZ2U",
                pubKeyCredParams: [
                    { alg: -7, type: "public-key" },
                    { alg: -257, type: "public-key" },
                ],
                rp: { id: "example.auth0.com", name: "My Application" },
                timeout: 60000,
                user: { id: "YXV0aDB8NTA3ZjFmNzdiY2Y4NmNkNzk5NDM5MDEx", name: "user@example.com", displayName: "User" },
            },
        };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.create({
            type: "phone",
            phone_number: "phone_number",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (15)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "passkey" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.create({
                type: "passkey",
            });
        }).rejects.toThrow(MyAccount.BadRequestError);
    });

    test("create (16)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "passkey" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.create({
                type: "passkey",
            });
        }).rejects.toThrow(MyAccount.UnauthorizedError);
    });

    test("create (17)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "passkey" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.create({
                type: "passkey",
            });
        }).rejects.toThrow(MyAccount.ForbiddenError);
    });

    test("create (18)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "passkey" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.create({
                type: "passkey",
            });
        }).rejects.toThrow(MyAccount.UnsupportedMediaTypeError);
    });

    test("create (19)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "passkey" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/authentication-methods")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.create({
                type: "passkey",
            });
        }).rejects.toThrow(MyAccount.TooManyRequestsError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "phone",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            phone_number: "phone_number",
            preferred_authentication_method: "sms",
        };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.get("authentication_method_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "email",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            email: "email",
        };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.get("authentication_method_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "totp",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
        };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.get("authentication_method_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "push-notification",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
        };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.get("authentication_method_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "recovery-code",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.get("authentication_method_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "password",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            identity_user_id: "identity_user_id",
            last_password_reset: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.get("authentication_method_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "passkey",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            credential_backed_up: true,
            credential_device_type: "multi_device",
            identity_user_id: "identity_user_id",
            key_id: "key_id",
            public_key: "public_key",
            transports: ["internal"],
            user_agent: "Chrome 131.0.0 / Mac OS X 10.15.7",
            user_handle: "user_handle",
            aaguid: "aaguid",
            relying_party_id: "relying_party_id",
            last_auth_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.get("authentication_method_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "webauthn-platform",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            key_id: "key_id",
            public_key: "public_key",
        };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.get("authentication_method_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "webauthn-roaming",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            key_id: "key_id",
            public_key: "public_key",
        };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.get("authentication_method_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.get("authentication_method_id");
        }).rejects.toThrow(MyAccount.BadRequestError);
    });

    test("get (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.get("authentication_method_id");
        }).rejects.toThrow(MyAccount.UnauthorizedError);
    });

    test("get (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.get("authentication_method_id");
        }).rejects.toThrow(MyAccount.ForbiddenError);
    });

    test("get (13)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.get("authentication_method_id");
        }).rejects.toThrow(MyAccount.NotFoundError);
    });

    test("get (14)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.get("authentication_method_id");
        }).rejects.toThrow(MyAccount.TooManyRequestsError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.authenticationMethods.delete("authentication_method_id");
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .delete("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.delete("authentication_method_id");
        }).rejects.toThrow(MyAccount.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .delete("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.delete("authentication_method_id");
        }).rejects.toThrow(MyAccount.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .delete("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.delete("authentication_method_id");
        }).rejects.toThrow(MyAccount.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .delete("/authentication-methods/authentication_method_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.delete("authentication_method_id");
        }).rejects.toThrow(MyAccount.TooManyRequestsError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "password",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            identity_user_id: "identity_user_id",
            last_password_reset: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.update("authentication_method_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.update("authentication_method_id");
        }).rejects.toThrow(MyAccount.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.update("authentication_method_id");
        }).rejects.toThrow(MyAccount.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.update("authentication_method_id");
        }).rejects.toThrow(MyAccount.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.update("authentication_method_id");
        }).rejects.toThrow(MyAccount.UnsupportedMediaTypeError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .patch("/authentication-methods/authentication_method_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.update("authentication_method_id");
        }).rejects.toThrow(MyAccount.TooManyRequestsError);
    });

    test("verify (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", otp_code: "123456" };
        const rawResponseBody = {
            type: "phone",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            phone_number: "phone_number",
            preferred_authentication_method: "sms",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            otp_code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", otp_code: "123456" };
        const rawResponseBody = {
            type: "phone",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            phone_number: "phone_number",
            preferred_authentication_method: "sms",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            otp_code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", otp_code: "123456" };
        const rawResponseBody = {
            type: "phone",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            phone_number: "phone_number",
            preferred_authentication_method: "sms",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            otp_code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed..." };
        const rawResponseBody = {
            type: "phone",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            phone_number: "phone_number",
            preferred_authentication_method: "sms",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed..." };
        const rawResponseBody = {
            type: "phone",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            phone_number: "phone_number",
            preferred_authentication_method: "sms",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", new_password: "MySecureP@ssw0rd!" };
        const rawResponseBody = {
            type: "phone",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            phone_number: "phone_number",
            preferred_authentication_method: "sms",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            new_password: "MySecureP@ssw0rd!",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            auth_session: "Fe26.2**05c400ed...",
            authn_response: {
                clientExtensionResults: { key: "value" },
                id: "dGVzdC1jcmVkZW50aWFsLWlk",
                rawId: "dGVzdC1jcmVkZW50aWFsLWlk",
                response: {
                    attestationObject: "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YQ...",
                    clientDataJSON: "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hh...",
                },
                type: "public-key",
            },
        };
        const rawResponseBody = {
            type: "phone",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            phone_number: "phone_number",
            preferred_authentication_method: "sms",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            authn_response: {
                clientExtensionResults: {
                    key: "value",
                },
                id: "dGVzdC1jcmVkZW50aWFsLWlk",
                rawId: "dGVzdC1jcmVkZW50aWFsLWlk",
                response: {
                    attestationObject: "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YQ...",
                    clientDataJSON: "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hh...",
                },
                type: "public-key",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", otp_code: "123456" };
        const rawResponseBody = {
            type: "phone",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            phone_number: "phone_number",
            preferred_authentication_method: "sms",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            otp_code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", otp_code: "123456" };
        const rawResponseBody = {
            type: "email",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
            email: "email",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            otp_code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", otp_code: "123456" };
        const rawResponseBody = {
            type: "totp",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            otp_code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", otp_code: "123456" };
        const rawResponseBody = {
            type: "push-notification",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
            name: "name",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            otp_code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (12)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", otp_code: "123456" };
        const rawResponseBody = {
            type: "recovery-code",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            confirmed: true,
            last_auth_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            otp_code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (13)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", otp_code: "123456" };
        const rawResponseBody = {
            type: "password",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            identity_user_id: "identity_user_id",
            last_password_reset: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            otp_code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (14)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "Fe26.2**05c400ed...", otp_code: "123456" };
        const rawResponseBody = {
            type: "passkey",
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            usage: ["primary"],
            credential_backed_up: true,
            credential_device_type: "multi_device",
            identity_user_id: "identity_user_id",
            key_id: "key_id",
            public_key: "public_key",
            transports: ["internal"],
            user_agent: "Chrome 131.0.0 / Mac OS X 10.15.7",
            user_handle: "user_handle",
            aaguid: "aaguid",
            relying_party_id: "relying_party_id",
            last_auth_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authenticationMethods.verify("authentication_method_id", {
            auth_session: "Fe26.2**05c400ed...",
            otp_code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (15)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            auth_session: "auth_session",
            authn_response: {
                id: "id",
                rawId: "rawId",
                response: { attestationObject: "attestationObject", clientDataJSON: "clientDataJSON" },
                type: "public-key",
            },
        };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.verify("authentication_method_id", {
                auth_session: "auth_session",
                authn_response: {
                    id: "id",
                    rawId: "rawId",
                    response: {
                        attestationObject: "attestationObject",
                        clientDataJSON: "clientDataJSON",
                    },
                    type: "public-key",
                },
            });
        }).rejects.toThrow(MyAccount.BadRequestError);
    });

    test("verify (16)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            auth_session: "auth_session",
            authn_response: {
                id: "id",
                rawId: "rawId",
                response: { attestationObject: "attestationObject", clientDataJSON: "clientDataJSON" },
                type: "public-key",
            },
        };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.verify("authentication_method_id", {
                auth_session: "auth_session",
                authn_response: {
                    id: "id",
                    rawId: "rawId",
                    response: {
                        attestationObject: "attestationObject",
                        clientDataJSON: "clientDataJSON",
                    },
                    type: "public-key",
                },
            });
        }).rejects.toThrow(MyAccount.UnauthorizedError);
    });

    test("verify (17)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            auth_session: "auth_session",
            authn_response: {
                id: "id",
                rawId: "rawId",
                response: { attestationObject: "attestationObject", clientDataJSON: "clientDataJSON" },
                type: "public-key",
            },
        };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.verify("authentication_method_id", {
                auth_session: "auth_session",
                authn_response: {
                    id: "id",
                    rawId: "rawId",
                    response: {
                        attestationObject: "attestationObject",
                        clientDataJSON: "clientDataJSON",
                    },
                    type: "public-key",
                },
            });
        }).rejects.toThrow(MyAccount.ForbiddenError);
    });

    test("verify (18)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            auth_session: "auth_session",
            authn_response: {
                id: "id",
                rawId: "rawId",
                response: { attestationObject: "attestationObject", clientDataJSON: "clientDataJSON" },
                type: "public-key",
            },
        };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.verify("authentication_method_id", {
                auth_session: "auth_session",
                authn_response: {
                    id: "id",
                    rawId: "rawId",
                    response: {
                        attestationObject: "attestationObject",
                        clientDataJSON: "clientDataJSON",
                    },
                    type: "public-key",
                },
            });
        }).rejects.toThrow(MyAccount.UnsupportedMediaTypeError);
    });

    test("verify (19)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            auth_session: "auth_session",
            authn_response: {
                id: "id",
                rawId: "rawId",
                response: { attestationObject: "attestationObject", clientDataJSON: "clientDataJSON" },
                type: "public-key",
            },
        };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/authentication-methods/authentication_method_id/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authenticationMethods.verify("authentication_method_id", {
                auth_session: "auth_session",
                authn_response: {
                    id: "id",
                    rawId: "rawId",
                    response: {
                        attestationObject: "attestationObject",
                        clientDataJSON: "clientDataJSON",
                    },
                    type: "public-key",
                },
            });
        }).rejects.toThrow(MyAccount.TooManyRequestsError);
    });
});
