// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../mock-server/MockServerPool";
import { MyAccountClient } from "../../src/Client";
import * as MyAccount from "../../src/api/index";

describe("ConnectedAccounts", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { connection: "connection", redirect_uri: "redirect_uri" };
        const rawResponseBody = {
            connect_uri: "connect_uri",
            auth_session: "auth_session",
            connect_params: { ticket: "ticket" },
            expires_in: 1,
        };
        server
            .mockEndpoint()
            .post("/connected-accounts/connect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connectedAccounts.create({
            connection: "connection",
            redirect_uri: "redirect_uri",
        });
        expect(response).toEqual({
            connect_uri: "connect_uri",
            auth_session: "auth_session",
            connect_params: {
                ticket: "ticket",
            },
            expires_in: 1,
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { connection: "x", redirect_uri: "redirect_uri" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .post("/connected-accounts/connect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connectedAccounts.create({
                connection: "x",
                redirect_uri: "redirect_uri",
            });
        }).rejects.toThrow(MyAccount.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { connection: "x", redirect_uri: "redirect_uri" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .post("/connected-accounts/connect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connectedAccounts.create({
                connection: "x",
                redirect_uri: "redirect_uri",
            });
        }).rejects.toThrow(MyAccount.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { connection: "x", redirect_uri: "redirect_uri" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .post("/connected-accounts/connect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connectedAccounts.create({
                connection: "x",
                redirect_uri: "redirect_uri",
            });
        }).rejects.toThrow(MyAccount.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { connection: "x", redirect_uri: "redirect_uri" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .post("/connected-accounts/connect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connectedAccounts.create({
                connection: "x",
                redirect_uri: "redirect_uri",
            });
        }).rejects.toThrow(MyAccount.TooManyRequestsError);
    });

    test("complete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            auth_session: "auth_session",
            connect_code: "connect_code",
            redirect_uri: "redirect_uri",
        };
        const rawResponseBody = {
            id: "id",
            connection: "connection",
            access_type: "offline",
            scopes: ["scopes"],
            created_at: "2024-01-15T09:30:00Z",
            expires_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/connected-accounts/complete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connectedAccounts.complete({
            auth_session: "auth_session",
            connect_code: "connect_code",
            redirect_uri: "redirect_uri",
        });
        expect(response).toEqual({
            id: "id",
            connection: "connection",
            access_type: "offline",
            scopes: ["scopes"],
            created_at: "2024-01-15T09:30:00Z",
            expires_at: "2024-01-15T09:30:00Z",
        });
    });

    test("complete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "auth_session", connect_code: "x", redirect_uri: "redirect_uri" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .post("/connected-accounts/complete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connectedAccounts.complete({
                auth_session: "auth_session",
                connect_code: "x",
                redirect_uri: "redirect_uri",
            });
        }).rejects.toThrow(MyAccount.BadRequestError);
    });

    test("complete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "auth_session", connect_code: "x", redirect_uri: "redirect_uri" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .post("/connected-accounts/complete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connectedAccounts.complete({
                auth_session: "auth_session",
                connect_code: "x",
                redirect_uri: "redirect_uri",
            });
        }).rejects.toThrow(MyAccount.UnauthorizedError);
    });

    test("complete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "auth_session", connect_code: "x", redirect_uri: "redirect_uri" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .post("/connected-accounts/complete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connectedAccounts.complete({
                auth_session: "auth_session",
                connect_code: "x",
                redirect_uri: "redirect_uri",
            });
        }).rejects.toThrow(MyAccount.ForbiddenError);
    });

    test("complete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyAccountClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { auth_session: "auth_session", connect_code: "x", redirect_uri: "redirect_uri" };
        const rawResponseBody = { type: "type", status: 1.1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .post("/connected-accounts/complete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connectedAccounts.complete({
                auth_session: "auth_session",
                connect_code: "x",
                redirect_uri: "redirect_uri",
            });
        }).rejects.toThrow(MyAccount.TooManyRequestsError);
    });
});
