// This file was auto-generated by Fern from our API Definition.

import * as MyAccount from "../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateAuthenticationMethodRequestContent {
    /** The friendly name of the authentication method */
    name?: string;
    /** The preferred authentication method (for phone authenticators) */
    preferred_authentication_method?: MyAccount.PhoneAuthenticationMethodEnum;
}

/**
 * @example
 *     {
 *         connection: "connection",
 *         redirect_uri: "redirect_uri"
 *     }
 */
export interface CreateConnectedAccountsRequestContent {
    /** The name of the connection to link the account with (e.g., 'google-oauth2', 'facebook'). */
    connection: string;
    /** The URI to redirect to after the connection process completes. */
    redirect_uri: string;
    /** An opaque value used to maintain state between the request and callback. */
    state?: string;
    /** The PKCE code challenge derived from the code verifier. */
    code_challenge?: string;
    /** The method used to derive the code challenge. Required when code_challenge is provided. */
    code_challenge_method?: CreateConnectedAccountsRequestContent.CodeChallengeMethod;
    /** Defines the permissions that the client requests from the Identity Provider. Must include the standard scopes used to identify the user (e.g. 'openid', 'email', 'profile'), the scope required to obtain refresh tokens if needed (e.g. 'offline_access'), and any custom scopes the client needs to access protected resources. */
    scopes?: string[];
    authorization_params?: MyAccount.AuthorizationParams;
}

export namespace CreateConnectedAccountsRequestContent {
    /** The method used to derive the code challenge. Required when code_challenge is provided. */
    export const CodeChallengeMethod = {
        S256: "S256",
    } as const;
    export type CodeChallengeMethod = (typeof CodeChallengeMethod)[keyof typeof CodeChallengeMethod];
}

/**
 * @example
 *     {
 *         auth_session: "auth_session",
 *         connect_code: "connect_code",
 *         redirect_uri: "redirect_uri"
 *     }
 */
export interface CompleteConnectedAccountsRequestContent {
    /** The authentication session identifier */
    auth_session: string;
    /** The authorization code returned from the connect flow */
    connect_code: string;
    /** The redirect URI used in the original request */
    redirect_uri: string;
    /** The PKCE code verifier */
    code_verifier?: string;
}

/**
 * @example
 *     {
 *         connection: "connection",
 *         from: "from",
 *         take: 1
 *     }
 */
export interface ListConnectedAccountsRequestParameters {
    /** Filter connected accounts by connection names */
    connection?: MyAccount.ConnectionNamesFilter | null;
    /** Cursor for pagination - start retrieving results from this point */
    from?: string | null;
    /** Number of results to return (1-20) */
    take?: number | null;
}

/**
 * @example
 *     {
 *         from: "from",
 *         take: 1
 *     }
 */
export interface ListConnectedAccountsConnectionsRequestParameters {
    /** Cursor for pagination - start retrieving results from this point */
    from?: string | null;
    /** Number of results to return (1-20) */
    take?: number | null;
}
