// This file was auto-generated by Fern from our API Definition.

import { AuthenticationMethodsClient } from "./api/resources/authenticationMethods/client/Client.js";
import { ConnectedAccountsClient } from "./api/resources/connectedAccounts/client/Client.js";
import { FactorsClient } from "./api/resources/factors/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";
import * as environments from "./environments.js";

export declare namespace MyAccountClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MyAccountClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MyAccountClient.Options>;
    protected _factors: FactorsClient | undefined;
    protected _authenticationMethods: AuthenticationMethodsClient | undefined;
    protected _connectedAccounts: ConnectedAccountsClient | undefined;

    constructor(options: MyAccountClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get factors(): FactorsClient {
        return (this._factors ??= new FactorsClient(this._options));
    }

    public get authenticationMethods(): AuthenticationMethodsClient {
        return (this._authenticationMethods ??= new AuthenticationMethodsClient(this._options));
    }

    public get connectedAccounts(): ConnectedAccountsClient {
        return (this._connectedAccounts ??= new ConnectedAccountsClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
