// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { ConnectedAccounts } from "./api/resources/connectedAccounts/client/Client.js";

export declare namespace MyAccountClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MyAccountClient {
    protected readonly _options: MyAccountClient.Options;
    protected _connectedAccounts: ConnectedAccounts | undefined;

    constructor(_options: MyAccountClient.Options) {
        this._options = _options;
    }

    public get connectedAccounts(): ConnectedAccounts {
        return (this._connectedAccounts ??= new ConnectedAccounts(this._options));
    }
}
