// This file was auto-generated by Fern from our API Definition.

export const Auth0MyAccountEnvironment = {
    Default: "https://auth0.auth0.com/me/v1",
} as const;

export type Auth0MyAccountEnvironment = typeof Auth0MyAccountEnvironment.Default;
