// This file was auto-generated by Fern from our API Definition.

export const MyAccountEnvironment = {
    Default: "https://auth0.auth0.com/me/v1",
} as const;

export type MyAccountEnvironment = typeof MyAccountEnvironment.Default;
