// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import * as environments from "../../../../../../environments.js";
import * as core from "../../../../../../core/index.js";
import * as Auth0MyAccount from "../../../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as errors from "../../../../../../errors/index.js";

export declare namespace Connections {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Connections {
    protected readonly _options: Connections.Options;

    constructor(_options: Connections.Options = {}) {
        this._options = _options;
    }

    /**
     * Retrieve available connections that can be used for account linking by the authenticated user.
     *
     * @param {Auth0MyAccount.ListConnectedAccountsConnectionsRequestParameters} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Auth0MyAccount.BadRequestError}
     * @throws {@link Auth0MyAccount.UnauthorizedError}
     * @throws {@link Auth0MyAccount.ForbiddenError}
     * @throws {@link Auth0MyAccount.TooManyRequestsError}
     *
     * @example
     *     await client.connectedAccounts.connections.list({
     *         from: "from",
     *         take: 1
     *     })
     */
    public async list(
        request: Auth0MyAccount.ListConnectedAccountsConnectionsRequestParameters = {},
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.Page<Auth0MyAccount.ConnectedAccountConnection>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Auth0MyAccount.ListConnectedAccountsConnectionsRequestParameters,
            ): Promise<core.WithRawResponse<Auth0MyAccount.ListConnectedAccountsConnectionsResponseContent>> => {
                const _metadata: core.EndpointMetadata = {
                    security: [{ "Bearer-DPoP": ["read:me:connected_accounts"] }],
                };
                const { from: from_, take = 10 } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (from_ !== undefined) {
                    _queryParams["from"] = from_;
                }
                if (take !== undefined) {
                    _queryParams["take"] = take?.toString() ?? null;
                }
                let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    this._options?.headers,
                    mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader(_metadata) }),
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.Auth0MyAccountEnvironment.Default,
                        "connected-accounts/connections",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    endpointMetadata: _metadata,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Auth0MyAccount.ListConnectedAccountsConnectionsResponseContent,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Auth0MyAccount.BadRequestError(
                                _response.error.body as Auth0MyAccount.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Auth0MyAccount.UnauthorizedError(
                                _response.error.body as Auth0MyAccount.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Auth0MyAccount.ForbiddenError(
                                _response.error.body as Auth0MyAccount.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Auth0MyAccount.TooManyRequestsError(
                                _response.error.body as Auth0MyAccount.ErrorResponse,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.Auth0MyAccountError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.Auth0MyAccountError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.Auth0MyAccountTimeoutError(
                            "Timeout exceeded when calling GET /connected-accounts/connections.",
                        );
                    case "unknown":
                        throw new errors.Auth0MyAccountError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Pageable<
            Auth0MyAccount.ListConnectedAccountsConnectionsResponseContent,
            Auth0MyAccount.ConnectedAccountConnection
        >({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.next != null && !(typeof response?.next === "string" && response?.next === ""),
            getItems: (response) => response?.connections ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "from", response?.next));
            },
        });
    }

    protected async _getAuthorizationHeader(endpointMetadata: core.EndpointMetadata): Promise<string | undefined> {
        const bearer = await core.EndpointSupplier.get(this._options.token, { endpointMetadata });
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
